import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./components/provider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body className={inter.className + " min-h-screen"} style={{
				background: "transparent url('paper.jpg') center top repeat",
			}}>
				<div className="page opacity-90 mx-auto my-4">
					<Provider>
						<Suspense>{children}</Suspense>
					</Provider>
				</div>
				<script id="script_metafixer" defer dangerouslySetInnerHTML={{
					__html: `(${function () {
						// FIXME: 적절하지 않은 코딩기법
						document.querySelector('meta[name="viewport"]')!.setAttribute('content', "width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover");
						setTimeout(() => {
							const script = document.querySelector('#script_metafixer');
							if (script?.parentNode) script.parentNode.removeChild(script);
						}, 1000);
					}})()`
				}} />
			</body>
		</html>
	);
}